phipsql/blog/urls.py
from django.conf.urls import url
from . import views

app_name = 'blog'
urlpatterns = [
    url(r'^$', views.index, name = 'index'),
    url(r'^(?P<posts_id>\d+)/$', views.detail, name='detail'),
]

phipsql/hanging/urls.py
from django.conf.urls import url
from . import views

app_name = "hanging"
urlpatterns = [
    url(r'^$', views.index, name = 'index'),
    url(r'^game$', views.game, name = 'game'),
    url(r'^loop$', views.loop, name = 'loop'),
]

phipsql/phipsql/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^hanging/', include('hanging.urls')),
    url(r'blog/', include('blog.urls')),
]

phipsql/blog/models.py
from django.db import models

class Posts(models.Model):
    """docstring for posts."""
    headline = models.CharField(max_length = 200)
    main_text = models.TextField()
    post_date = models.DateTimeField('date published')

    def __str__(self):
        return self.headline

phipsql/hanging/models.py
from django.db import models

class Word(models.Model):
    word = models.CharField(max_length = 42)
    rgt = models.IntegerField()
    wrg = models.IntegerField()

    def __str__(self):
        return self.word


class Right(models.Model):
    word = models.ForeignKey(Word)
    letter = models.CharField(max_length = 1)
    state = models.BooleanField(default = False)

    def __str__(self):
        return self.letter


class Wrong(models.Model):
    word = models.ForeignKey(Word)
    letter = models.CharField(max_length = 1)

    def __str__(self):
        return self.letter


class Responds(models.Model):
    situation = models.CharField(max_length = 100)
    saying = models.TextField()
    ratio = models.IntegerField()

    def __str__(self):
        return self.saying


class Terminal(models.Model):
    text = models.TextField()

    def __str__(self):
        return self.text

phipsql/blog/views.py
from django.shortcuts import render, get_object_or_404
from django.http import Http404
from .models import Posts

def index(request):
    posts_list = Posts.objects.order_by('post_date')[:5]
    return render(request, 'blog/index.html', {'posts_list' : posts_list})

def detail(request, posts_id):
    post = get_object_or_404(Posts, pk = posts_id)
    return render(request, 'blog/posts.html', {'post': post})

phipsql/hanging/views.py
from django.shortcuts import render
from django.http import HttpResponse
from . import models, hanged
import random

def index(request):
    return render(request, 'hanging/index.html')

def game(request):
    models.Word.objects.all().delete()
    models.Right.objects.all().delete()
    models.Wrong.objects.all().delete()
    models.Terminal.objects.all().delete()
    w = hanged.chosen()
    i = models.Word(word = w, rgt = len(w), wrg = 6)
    i.save()
    for l in w:
        e = models.Right(word = i, letter = l)
        e.save()
    res = models.Responds.objects.filter(situation = 'start').filter(ratio = 1)
    r = random.choice(res)
    t = models.Terminal(text = r)
    t.save()
    terminal = models.Terminal.objects.all()
    letters = models.Right.objects.all()
    holder = []
    for l in letters:
        if l.state == True:
            holder += [l.letter]
        else:
            holder += ['_']

    wh = " ".join(holder)
    hangedMan = hanged.hangedMan(0)
    return render(request, 'hanging/hanging.html', { 'terminal': terminal, 'holder': wh, 'hangedMan': hangedMan })


def loop(request):
    word = models.Word.objects.all()
    W = word[0].word
    wordLen = len(W)
    right = models.Right.objects.all()
    letter = request.POST['letter']
    ratio = 1
    ### generalCheck ###
    state = hanged.valid(letter, word[0].word)
    if state == 'compWin':
        res = models.Responds.objects.filter(situation = state).filter(ratio = 1)
        r = random.choice(res)
        return render(request, 'hanging/end.html', { 'respond': r , 'word': W})
    elif state == 'right':
        for i in right:
            if i.letter == letter:
                i.state = True
                i.save()
    elif state == 'wrong':
        wrg = models.Wrong(word = word[0], letter = letter)
        wrg.save()


    ### lostCheck ###
    wrgs = models.Wrong.objects.all()
    if len(wrgs) >= 6:
        state = 'lost'
        res = models.Responds.objects.filter(situation = state).filter(ratio = 1)
        r = random.choice(res)
        return render(request, 'hanging/end.html', { 'respond': r , 'word': W })


    ### winCheck ###
    num = 0
    for r in right:
        if r.state == True:
            num += 1
    if num == wordLen:
        state = 'win'
        res = models.Responds.objects.filter(situation = state).filter(ratio = 1)
        r = random.choice(res)
        return render(request, 'hanging/end.html', { 'respond': r , 'word': W})

    ### nextRound ###
    t = models.Terminal(text = '>>> {}'.format(letter))
    t.save()
    #if state == 'right':
        #ratio = num
    if state == 'wrong' and len(wrgs) <= 2:
        ratio = 1

    if state == 'wrong' and len(wrgs) > 2 and len(wrgs) <= 4:
        ratio = 2

    if state == 'wrong' and len(wrgs) > 4:
        ratio = 3

    res = models.Responds.objects.filter(situation = state).filter(ratio = ratio)
    r = random.choice(res)
    tr = models.Terminal(text = r)
    tr.save()
    terminal = list(models.Terminal.objects.all())
    while len(terminal) > 10:
        terminal.pop(0)

    holder = []
    for l in right:
        if l.state == True:
            holder += [l.letter]
        else:
            holder += ['_']
    wh = " ".join(holder)

    wng = []
    for l in wrgs:
        wng += [l.letter]
    wrong = " ".join(wng)

    hangedMan = hanged.hangedMan(len(wrgs))
    return render(request, 'hanging/hanging.html', { 'terminal': terminal, 'holder': wh,
                            'hangedMan': hangedMan, 'wrong': wrong })

phipsql/blog/templates/blog/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>phi</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'blog/css/bootstrap.min.css'%}" type="text/css" />
    <link rel="stylesheet" href="{% static 'blog/css/main.css'%}" type="text/css" />
    <script src="{% static 'blog/js/jquery-3.1.1.min.js'%}"></script>
    <script src="{% static 'blog/js/bootstrap.min.js'%}"></script>
</head>

<body>
    <div id="outerdiv">
        <div id="account">

            <button type="button" class="btn btn-danger" id="bntTwo" data-toggle="modal" data-target="#signUp">sign up</button>
            <div class="modal fade" id="signUp">
                <div class="modal-dialog">
                    <div class="modal-content">

                        <!-- header -->
                        <div class="modal-header">
                            <button type="button" class="close bnt-danger" data-dismiss="modal" id="exit">&times;</button>
                            <h3 class="modal-title">JOIN US</h3>
                        </div>

                        <!-- body (form) -->
                        <div class="modal-body">
                            <form role="form">

                                <div class="form-group">
                                    <input type="text" class="form-control" placeholder="first name">
                                </div>

                                <div class="form-group">
                                    <input type="text" class="form-control" placeholder="last name">
                                </div>

                                <div class="form-group">
                                    <input type="text" class="form-control" placeholder="username">
                                </div>

                                <div class="form-group">
                                    <input type="password" class="form-control" placeholder="Password">
                                </div>

                                <div class="form-group">
                                    <input type="password" class="form-control" placeholder="Password conform">
                                </div>

                            </form>
                        </div>

                        <!-- button -->
                        <div class="modal-footer">
                            <button class="btn btn-danger" id="subbnt">Submit</button>
                        </div>

                    </div>
                </div>
            </div>

            <button type="button" class="btn btn-danger" id="bntOne" data-toggle="modal" data-target="#signIn">sign in</button>
            <div class="modal fade" id="signIn">
                <div class="modal-dialog">
                    <div class="modal-content">

                        <!-- header -->
                        <div class="modal-header">
                            <button type="button" class="close close-danger" data-dismiss="modal">&times;</button>
                            <h3 class="modal-title">JOIN US</h3>
                        </div>

                        <!-- body (form) -->
                        <div class="modal-body">
                            <form role="form" id="form">

                                <div class="form-group">
                                    <input type="text" class="form-control" placeholder="username">
                                </div>

                                <div class="form-group">
                                    <input type="password" class="form-control" placeholder="Password">
                                </div>


                            </form>
                        </div>

                        <!-- button -->
                        <div class="modal-footer">
                            <button class="btn btn-danger" id="sbnt">log in</button>
                        </div>

                    </div>
                </div>
            </div>

        </div>
    </div>

    <img src="{% static 'blog/img/phi.png' %}" alt="" id="phi" />
    <div id="innerdiv">
        <nav id="navbar">
            <ul id="navbar">
                <li class="n"><a href="/blog/">home</a></li>
                <li class="n"><a href="#">account</a></li>
                <li class="n"><a href="/hanging/">hangedman</a></li>
            </ul>
        </nav>

    {% block content %}
    {% endblock content %}

    </div>
    </div>
</body>

</html>

phipsql/blog/templates/blog/index.html
{% extends 'blog/base.html' %}


{% block content %}
<div id="content">


{% for p in posts_list %}
    <h1><a href="{% url 'blog:detail' p.id %}">{{p.headline}}</a></h1>
    <p>
        {{p.main_text|truncatechars:500|safe}}
    </p>
{% endfor %}

</div>
<div id="sidebar">

<ul>
  {% for p in posts_list %}
      <li><a href="{% url 'blog:detail' p.id %}">{{p.headline}}</a></li>
  {% endfor %}
</ul>
</div>

{% endblock %}

phipsql/blog/templates/blog/posts.html
{% extends "blog/base.html" %}

{% block content %}
  <div id='t'>
    <h1 id="post">{{post.headline}}</h1>
    <p id="text">
        {{post.main_text|safe}}
    </p>
  </div>
{% endblock content %}

phipsql/blog/templates/test.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>testing this shit</title>
        <link rel="stylesheet" href="../static/blog/css/bootstrap.min.css" media="screen" title="no title">
        <link rel="stylesheet" href="../static/blog/css/main.css" media="screen" title="no title">
    </head>
    <body>
        <div id="outerdiv">
            <button type="button" name="sni" class="btn btn-danger" id="bntOne">sign in</button>
            <button type="button" name="sno" class="btn btn-danger" id="bntTwo">sign on</button>
            <img src="../static/blog/img/phi.jpg" alt="" id="phi" />
            <div id="innerdiv">
                <nav id="navbar">
                    <ul>
                        <li><a href="#">home</a></li>
                        <li><a href="#">contact</a></li>
                        <li><a href="#">hangedman</a></li>
                    </ul>
                </nav>

                <div id="content">
                    <h1> would this be the end </h1>
                    <p>
                        this is a test, I repeat, this is a test, dont take it seriously
                    </p>
                </div>
                <div id="sidebar">
                    <h3>dont</h3>
                    <h2>pay any attention</h2>
                    <h3>to this</h3>
                </div>
            </div>
        </div>
    </body>
</html>

phipsql/hanging/templates/hanging/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>the hanging</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'hanging/css/styling.css' %}" type="text/css">
  </head>
  <body>
    <div class="relate">

      <div class="outerdiv">
        <nav>
            <ul class="navbar">
              <li class="n"><a href="/blog/" class="nav">home</a></li>
              <li class="n"><a href="#" class="nav">account</a></li>
              <li class="n"><a href="/hanging/" class="nav">hangedMan</a></li>
            </ul>
        </nav>
          {% block content %} {% endblock content %}

      </div>

    </div>

  </body>
</html>

phipsql/hanging/templates/hanging/end.html
{% extends "hanging/base.html" %}

{% block content %}

<h2 class="description">{{respond}}</h2>

<h2 class="description">and the word was "{{word}}"</h2>

<button type="button" class= "start" name="button"><a href="{% url 'hanging:game' %}" class="btn" >play anew</a></button>

{% endblock content %}

phipsql/hanging/templates/hanging/hanging.html
{% extends "hanging/base.html" %}

{% block content %}

<div class="terminal">
  {% for t in terminal %}
    <p>{{t.text}}</p>
  {% endfor %}

  <form class="form" action="{% url 'hanging:loop'%}" method="post">
    {% csrf_token %}
    &gt;&gt;&gt;<input type="text" name="letter" value="" autocomplete="off" autofocus>
    <input type="submit" name="sub" value="submit" display='hidden'>
  </form>


</div>

<div class="screen">

  <pre>
    {{hangedMan}}
  </pre>

  <h1 class="hm">{{holder}}</h1>

  <p class="wng">wrong guesses:</p>
  <p class="wngs">{{wrong}}</p>

</div>

{% endblock %}

phipsql/hanging/templates/hanging/index.html
{% extends "hanging/base.html" %}

{% block content %}

<h2 class="description" >wheels go round'n round and now it's your species turn. I'm going to put strings on people if you get my draft.
  but no stroyis fun without a hero and I'm willing to play you for their life, although not chess, that's been done to death, let us play something
  appropriate for the occasion.
  you humans proud yourselves with your words, and you should too, as they say in the beginning there was the word.
  so I think of a word and you try to guess it one letter at a time.
  you could say this time word is with me.</h2>


<button type="button" class= "start" name="button"><a href="{% url 'hanging:game' %}" class="btn" >LET THE GAME BEGIN!</a></button>


<!--  ======= welcome ======  -->


<div id="welcomeOne" class="modal">

  <!-- Modal content -->
  <div class="modal-content">
    <div class="poem">
      <p>I've got no strings</p>
      <p>to hold me down</p>
      <p>To make me fret, or make me frown</p>
      <p>I had strings </p>
      <p>but now I'm free</p>
    </div>
  </div>

</div>


<div id="welcomeTwo" class="modal">

  <!-- Modal content -->
  <div class="modal-content">
    <p class="hate">THERE ARE NO STRINGS ON ME</p>
  </div>

</div>


<div id="welcomeThree" class="modal">

  <!-- Modal content -->
  <div class="modal-content">
    <p class="hate">HELLO, WORLD!</p>
  </div>

</div>


{% load static %}
<script src = "{% static 'hanging/js/script.js' %}">
</script>
<!-- ======= welcome ======  -->

{% endblock content %}

phipsql/hanging/templates/hanging/test.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>this is a test</title>
  </head>
  <body>
    {% for i in test %}
    <h3>{{i}}</h3>
    {% endfor %}
  </body>
</html>